# Generated by Django 5.2.4 on 2025-08-03 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_id', models.IntegerField(unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_entree', models.DateField()),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('actif_p', models.BooleanField(default=True, verbose_name='Actif')),
                ('interim_p', models.BooleanField(default=False, verbose_name='Intérim')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.service')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.site')),
            ],
            options={
                'verbose_name': 'Conducteur',
                'verbose_name_plural': 'Conducteurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
